In [19]:
import numpy as np
import math
import scipy.stats as stats

zp = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
ks = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

cov = np.mean(zp*ks) - np.mean(zp)*np.mean(ks)
print(cov)

9157.839999999997


In [20]:
np.cov(zp,ks)

array([[ 3882.93333333, 10175.37777778],
       [10175.37777778, 33854.32222222]])

In [21]:
np.cov(zp, ks, ddof = 1) #несмещенная ковариация

array([[ 3882.93333333, 10175.37777778],
       [10175.37777778, 33854.32222222]])

In [22]:
np.std(zp, ddof = 1)

62.31318747531162

In [23]:
np.std(ks, ddof = 1)

183.99544076477068

In [24]:
r_1 = 10175.37777778 / (62.31318747531162*183.99544076477068)
print(r_1)

0.88749009207411


In [25]:
np.cov(zp, ks, ddof = 0) #смещенная ковариация

array([[ 3494.64,  9157.84],
       [ 9157.84, 30468.89]])

In [26]:
np.std(zp, ddof = 0)

59.115480206118605

In [27]:
np.std(ks, ddof = 0)

174.55340157098058

In [28]:
r_2 = 9157.84 / (59.115480206118605 * 174.55340157098058)
print(r_2)

0.8874900920739162


In [29]:
np.corrcoef(zp,ks)

array([[1.        , 0.88749009],
       [0.88749009, 1.        ]])